ryu/d2s.c
This significantly improves the performance of the fallback case by computing the upper and lower bounds relative to the exact value, rather than doing additional multiplications. The fallback case requires quite a few multiplications (unlike the cases where we have 64x64 bit multiplications available), making this a significant win.
=> Improve fallback performance

ryu/d2s.c, ryu/mulshift128.h
warning C4244: conversion from 'uint64_t' to 'unsigned char', possible loss of data
This is emitted because the `__shiftright128` intrinsic is declared as taking `unsigned char`, and reappeared due to recent refactoring. Now, mulshift128.h is a centralized location where we can silence this warning.
(This also adds a newline to the end of mulshift128.h. My editor is configured to automatically do this, and some compilers warn when they see headers that don't end with newlines.)
=> Fix MSVC x64 truncation warning.

ryu/d2s.c, ryu/f2s.c
Printing 64-bit doubles on 32-bit platforms is the slowest scenario, but there's a simple way to improve this. Because the core Ryu algorithm is so fast, a relatively large amount of time is spent on the mundane task of decomposing an integer into decimal digits. This involves expensive 64-bit divisions, partially mitigated by the digit table. It's possible to do most of the work with cheap 32-bit divisions. The strategy is:
* When we detect a 32-bit platform, activate the new code. (I'm currently checking MSVC's platform macros, which I'm familiar with. Other platform macros can be added in the future. Note that I've phrased this preprocessor check so that unknown platforms use the original code. Alternatively, the preprocessor could be avoided by testing `sizeof(void *)` and using …
=> Make 64-bit printing on 32-bit platforms 9% to 12% faster.

ryu/f2s.c
This code was apparently copied from d2s.c where types are different. In f2s.c, vr is uint32_t, so vr / 10 can be stored in uint32_t. This doesn't affect the (vr - 10 * nvr) modulo workaround, and it avoids the need for casting when assigning back to vr.
=> nvr should be uint32_t in f2s.c.

ryu/d2s.c, ryu/digit_table.h, ryu/f2s.c
The comment for multipleOfPowerOf5() said "divides",
but it meant the reverse, "is divisible by".
Add periods to sentences for consistency with nearby list items.
Hyphenate "64x128-bit" and "two-digit" for consistency.
=> Comment fixes and cleanups.

ryu/d2s.c, ryu/f2s.c
NOTE: My understanding of the algorithm is incomplete, so I'm not
certain that this change is correct. I ran
`benchmark -samples=100000000 -iterations=1` with x86/x64 Clang/MSVC
and it always succeeded.
According to my understanding, vp contains the decimal digits before
trimming, while output contains the decimal digits after trimming.
vplength and olength contain how many decimal digits are in each
variable, with `removed` being the difference. (I'm more certain about
output and olength's behavior, since I can see how they're used in the
final digit-printing step, with olength being used to write the least
significant digits at the highest memory addresses first.)
I noticed that vplength is calculated early, but is almost unused until
`removed` is finished and used to calculate olength. …
=> Call decimalLength() with output instead of vp.

ryu/f2s.c
Some changes to improve the performance for d2s on x86 platforms.
Basically this adds a `mulShift` function like the one in the `d2s` implementation. 
For 32-bit platforms this function avoids 64-bit arithmetic. This greatly helps MSVC x86 to generate faster code.
The behavior (and performance) is unaffected for 64-bit.
On my test PC (64-bit) the performance improvements with MSVC x86 were ~20%. I haven't tested or benchmarked the code on a genuine 32-bit platform, though.
=> Small improvements for f2s (on x86 platforms)

ryu/mulshift128.h
Two minor changes which should improve the performance for `d2s` on x86 platforms
1. The shift count in `shiftright128` is always less than 64 in the current implementation. This allows to remove a branch in this function.
2. Added some 32/64-bit casts to `umul128`. This allows MSVC to avoid calls to the `__allmul` library function. This shouldn't affect codegen for other compilers (but I haven't checked).
I have tested the code using MSVC x86 (on Windows 10 x64, though) and the performance improvement was about 10%.  I haven't benchmarked (and tested) the code on genuine 32-bit platforms, though.
=> Small improvements for d2s (on x86 platforms)

ryu/BUILD, ryu/common.h, ryu/d2s.c, ryu/d2s.h, ryu/f2s.c, ryu/mulshift128.h
Add common.h to avoid code duplication. The implementations of
these functions were exactly identical.
Improve assertions and comments.
d2s.c:
* Update decimalLength()'s comment, as it's now called with trimmed
output.
* Add an assertion for decimalLength()'s precondition. Include assert.h
for this.
* Add a period to the "slightly faster" comment for consistency.
* Add parentheses to a comment for consistency with the actual code
(required by C's precedence rules).
f2s.c:
* In mulShift(), change assert(shift >= 32) to assert(shift > 32),
because shift == 32 would lead to a forbidden "full shift" below
(undefined behavior in C, with varying behavior between x86 and ARM).
Update the comment accordingly. This passed
`benchmark -samples=1000000000 -iterations=1` with assertions enabled.
* …
=> Add common.h, improve assertions and comments.

README.md
without "-l m" (linking to the maths library) I get "undefined reference to symbol 'sqrt@@GLIBC_2.2.5'" on Debian Stretch with gcc 6.3.0
=> C benchmark compilation requires "-l m"

ryu/d2s.c
This is based on the change by @m-ou-se, #35, but only a small part of it. As far as I can tell, this does not regress performance.
I'm not sure if a struct with three fields will ever be passed as two registers even if it's technically possible. However, we could reduce this to two fields by merging the sign into the digits field. We might want to experiment with that.
Progress on #30.
=> Add an intermediate rep between digit gen and string gen

ryu/common.h, ryu/d2s.c, ryu/f2s.c
This fixes a RYU_DEBUG compiler error which was recently introduced.
It also fixes MSVC warnings involving the recent addition of floating_decimal_64.
It adds const for consistency and safety.
Finally, it updates d2s/f2s comments to be consistent with each other.
=> Fix RYU_DEBUG and MSVC warnings, add const, cleanup comments.

src/main/java/info/adams/ryu/RyuFloat.java, src/main/java/info/adams/ryu/analysis/SlowConversion.java, src/test/java/info/adams/ryu/FloatToStringTest.java
There are two rounding cases; we already round even for the case where the
shortest value coincides with one of the bounds. However, we don't round even
if exact value is exactly half-way between two shortest values, i.e., if it
ends with an additional 5 digit, followed by zeroes.
Progress on #8.
=> Implement round-even for the Java 32-bit implementation

ryu/d2s.c
As proposed by @mitchblank, this introduces a 'presentation layer' and a
'conversion layer', with the former depending on the latter. The presentation
layer decodes the floating point number and then passes it to the conversion
layer to get the decimal digits (only if necessary). This implies that it has
the sign bit, so the floating decimal does not have to contain it.
For some unfathomable reason, this seems to be a bit faster.
=> Swap order of decimal digit gen and binary to decimal conv

src/main/java/info/adams/ryu/analysis/ComputeRequiredBitSizes.java, src/main/java/info/adams/ryu/analysis/FloatingPointFormat.java
This might be the beginning of support for 80-bit floating point numbers, as supported on Intel and compatible CPUs/FPUs.
Minimal progress on #13.
=> Add a FLOAT80 enum, and add a -80 flag to the bit size computer

ryu/d2s.c, ryu/f2s.c
Finish refactoring d2s.c with to_chars() like f2s.c.
---
Remove unnecessary casts.
d2s.c: After the recent refactoring, output2 is always uint32_t, so we don't need uint32_t casts for expressions involving it.
f2s.c: This expression was already uint32_t.
---
Minor cleanups.
d2s.c: Adjust comment indentation below "We would compute mp and mm".
Remove "The average output length is 16.38 digits" comment. After the recent refactoring, the rest of this function doesn't deal with printing digits, so this comment isn't needed here. (decimalLength() still contains this comment, where it is relevant.)
Similarly, remove the commented-out definition of olength. This exact line of code appears elsewhere.
f2s.c: Like d2s.c, collapse the definitions of vr, vp, vm to a single line. (I generally prefer …
=> Finish refactoring d2s.c with to_chars(), remove unnecessary casts.

ryu/d2s.c, ryu/f2s.c
Improve RYU_DEBUG.
* Add const.
* Fix GCC -Wformat-signedness warnings by printing uint32_t with "%u" instead of "%d".
* In f2s.c, print `e2 + 2` like d2s.c does. Fixes #47.
* Add RYU_DEBUG lines to f2s.c, appropriately modified from d2s.c.
---
Copy Clang workaround from d2s.c to f2s.c.
I observe that this improves x86 performance by 1%, although it doesn't appear to affect x64 performance.
=> Improve RYU_DEBUG, copy Clang workaround.

ryu/tests/f2s_test.cc
I constructed these inputs and outputs by hand (with assistance from
Wolfram Alpha) and verified via debugging that q == 10.
The inputs, converted from hex to binary, are:
0 10111010 00101010000001011111001
0 10111011 00101010000001011111001
0 10111100 00101010000001011111001
The mantissas are identical. After restoring the implicit leading bit,
this is 100101010000001011111001 in binary, or 9765625 in decimal,
which is 5^10. No multiples are possible: 5^10 is less than 2^24,
but 2 * 5^10 is greater.
The exponents in decimal are 186, 187, and 188, determined by solving
for q == 10:
q = log10Pow2(e2);
q = floor(log_10(2^e2)); (using the exact form, not the approximation)
Our ieeeExponent is nonzero, so:
e2 = ieeeExponent - bias - FLOAT_MANTISSA_BITS - 2;
e2 = ieeeExponent - 127 - 23 - 2; …
=> Add F2sTest LooksLikePow5.

ryu/d2s.c, ryu/f2s.c
This ports commits 6dd24a5, d5e4cd4, 87d807b, fab5f9d, and 4990e0f from d2s.c to f2s.c.
---
Fix signedness warnings.
Changing pow5Factor() to return uint32_t fixes MSVC warning C4018 "'>=': signed/unsigned mismatch" and Clang -Wsign-compare "warning: comparison of integers of different signs: 'int32_t' (aka 'int') and 'const uint32_t' (aka 'const unsigned int')".
Also fix GCC -Wformat-signedness by using %u to print uint32_t q.
---
Improve comments.
Copy mmShift comment from d2s.c to f2s.c.
In d2s.c multipleOfPowerOf2(), change the commented intrinsic from __builtin_ctz to __builtin_ctzll, which would correctly handle uint64_t value.
Change "mv = 4 m2" to "mv = 4 * m2" to match the source code.
Fix "exact number" pluralization.
=> Update f2s.c, fix signedness warnings, improve comments.

ryu/common.h, ryu/d2s.c, ryu/f2s.c
Remove the comments that refered to big-endian architectures - it should work
just fine as long as float and int use the same endianness.
Closes #3.
=> Move float/double to bits conversion to a helper method

ryu/benchmark/benchmark.cc
Avoiding strlen makes the benchmark more comparable across languages that would not want a null terminator, such as Rust.
This strlen in bench32 was 20% of the iteration time on my machine.
=> Remove strlen in C++ benchmark

ryu/d2s.c, ryu/f2s.c
On Reddit, the user Veedrac mentioned that my `while (vp - vm >= 1000)` loop never activated. Oops! I confirmed this (0 activations, for 1 billion random doubles), and instrumented the control flow to understand what was happening. (I've rediscovered the story behind the existing comment "On average, we remove ~2 digits.")
Although that loop was dead weight, my previous PR improved performance due to the `if (vp - vm >= 100)` branch. This is successful ~60.3% of the time (out of control flow that passes through the common case).
An even larger improvement is possible. The idea behind my subtraction optimization was that its inexactness (it misses cases when two digits can be removed) was counterbalanced by its cheapness when false (ignoring branch misprediction, it doesn't cost any …
=> d2s.c: Further improve x86 perf.

ryu/benchmark/benchmark.cc
This contains several improvements for benchmark.cc, grouped into separate commits for ease of reviewing. There are two new features:
* A `-ryu` option to run only Ryu without Grisu3. This is a time-saver when profiling Ryu changes.
* An `-invert` option to switch the sample/iteration loops. This should help to understand the impact of branch (mis)prediction on Ryu.
Commit notes:
---
benchmark.cc: Drop `if (throwaway == 12345)`.
This code was present in the float benchmarking, but not double. I suspect that it was a relic of an earlier era when throwaway wasn't returned to main() for inspection.
---
benchmark.cc: constexpr BUFFER_SIZE, avoid calloc().
BUFFER_SIZE should be a compile-time constant, not a modifiable global variable.
Instead of dynamically allocating memory (and never …
=> Improve benchmark.cc, adding -ryu and -invert options.

ryu/mulshift128.h
This form allows MSVC, clang and gcc to generate slightly more efficient
code.
The performance improvements are small, though: (MSVC x86)
Before:
```
Average & Stddev Ryu  Average & Stddev Grisu3
64:  183.224   24.041      473.238  288.589
64:  186.400   33.356      480.405  295.526
64:  183.176   23.788      472.911  281.405
64:  183.213   24.807      472.030  278.272
```
After:
```
Average & Stddev Ryu  Average & Stddev Grisu3
64:  176.233   24.209      475.512  267.100
64:  176.814   25.140      477.540  270.645
64:  176.339   24.525      475.089  268.061
64:  175.912   24.969      474.403  274.223
```
=> Slightly more efficient umul128 implementation

ryu/tests/d2s_test.cc
It appears that @abolz temporarily disabled these tests while working on new ones.
=> Restore d2s_test.cc coverage.

README.md
Also format the ever-growing list as a table.
Thanks for this algorithm and the implementation! Next I'm planning on changing the Go stdlib itself to use Ryu as its float formatting algorithm.
Two things I noticed while working on this:
- It seemed like one of the optimizations for handling two digits at a time might have been intended to be a loop rather than a single if statement. I brought this up over at #85.
- While comparing performance against the Go stdlib, I copied an optimization that's used there. If a float f represents an integer value and it is within the range where every integer is representable, then we can skip most of the expensive work and construct the decimal representation directly. (See [here](https://github.com/cespare/ryu/blob/ba56a33f39e3bbbfa409095d0f9ae168a595f …
=> Add github.com/cespare/ryu to list of implementations

ryu/d2fixed.c, ryu/d2fixed_full_table.h
These changes primarily improve mulShift(), activating the uint128 codepath for Clang/LLVM x64 targeting Windows, and improving uint128 perf (hopefully for Linux and Mac too) by 10.8% (for %f) and 7.9% (for %e). There's a small improvement from removing a special case for 0-shifting (previously removed for the non-uint128 codepaths), and a large improvement from implementing a 128-bit magic multiply.
Unlike the 64-bit magic multiplies, where we can just inspect Clang x64 codegen, I had to generate the 128-bit multiplier (`0x89705F4136B4A59731680A88F8953031`, written as two 64-bit constants) and shift value (`29`) myself, with the classic algorithm in Hacker's Delight. (The "add" indicator was 0, resulting in simpler code, happily.) The new helper functions `umul256()` and `umul256_hi()` …
=> Improve uint128 performance by 10.8% and 7.9%

ryu/d2s.c
This improves MSVC x86 perf by 2.1% and doesn't affect other platforms.
The early truncation technique was described here:
```
static inline uint32_t mod1e9(const uint64_t x) {
// Avoid 64-bit math as much as possible.
// Returning (uint32_t) (x - 1000000000 * div1e9(x)) would
// perform 32x64-bit multiplication and 64-bit subtraction.
// x and 1000000000 * div1e9(x) are guaranteed to differ by
// less than 10^9, so their highest 32 bits must be identical,
// so we can truncate both sides to uint32_t before subtracting.
// We can also simplify (uint32_t) (1000000000 * div1e9(x)).
// We can truncate before multiplying instead of after, as multiplying
// the highest 32 bits of div1e9(x) can't affect the lowest 32 bits.
return ((uint32_t) x) - 1000000000 * ((uint32_t) div1e9(x));
}
```
=> Avoid 64-bit math for remainders.

ryu/d2s_intrinsics.h
When concatenating two 32-bit values, MSVC's x86 codegen is affected by plus versus bitwise OR.
For plus, the codegen is:
```
add eax, DWORD PTR _b00$1$[esp+16]
adc edi, 0
```
That's an add followed by add-with-carry; i.e. the compiler is emitting a general 64 + 32 addition.
For bitwise OR, the codegen is:
```
or  eax, DWORD PTR _b00$1$[esp+16]
```
Bitwise OR is both conceptually simpler and more efficient.
=> Use bitwise OR in umul128() to improve codegen.

ryu/d2fixed.c, ryu/d2s_intrinsics.h
Improve perf and carry logic.
Compiler    | Before  | After
------------|---------|--------
MSVC x86 %f | 357.983 | 356.370
MSVC x86 %e | 107.619 | 105.532
LLVM x86 %f | 352.767 | 353.259
LLVM x86 %e | 104.455 | 104.600
Compiler    | Before  | After   | Speedup
------------|---------|---------|--------
MSVC x64 %f | 159.110 | 118.643 | 34.1%
MSVC x64 %e |  54.288 |  44.169 | 22.9%
LLVM x64 %f | 116.734 |  97.031 | 20.3%
LLVM x64 %e |  40.285 |  36.193 | 11.3%
LLVM 128 %f | 101.752 |  98.859 | 2.9%
LLVM 128 %e |  37.498 |  37.120 | 1.0%
Note that this slightly improves the "headline perf" of the algorithm. Comparing the previous fastest (LLVM uint128) to the new fastest (LLVM x64 intrinsics), %f is 4.9% faster, and %e is 3.6% faster.
Individual commits:
---
Use bitwise OR in umul128() to …
=> Improve perf and carry logic.

ryu/d2fixed.c
Compiler    | Before  | After   | Speedup
------------|---------|---------|--------
MSVC x86 %e | 105.350 | 103.466 | 1.8%
LLVM x86 %e | 104.851 | 102.818 | 2.0%
MSVC x64 %e | 44.677  | 42.745  | 4.5%
LLVM x64 %e | 36.165  | 34.617  | 4.5%
LLVM 128 %e | 36.321  | 35.462  | 2.4%
Previously, `d2exp_buffered_n` used `append_n_digits` to print the exponent. That's a general digit printer, so we ended up doing several expensive things:
* Calling `decimalLength9`, performing several branches before finding that the exponent is always 1, 2, or 3 digits.
* Performing more branches for exponent length. For example, `digits >= 10000` is always false. Then, if `digits >= 100` is true, we divide by 100 and test `digits >= 10`. That handles numbers that were originally 3 or 4 digits, but decimal …
=> Improve d2exp_buffered_n headline perf.

ryu/d2fixed.c, ryu/tests/d2fixed_test.cc
Individual commits:
---
Rename `max` to `maximum`.
This is an MSVC-specific thing; we have headers that macroize `max` and `__max`, so I want to avoid this particular identifier (even though the function-like macros aren't technically causing problems here).
`maximum` avoids this minor headache without affecting code clarity.
---
Avoid requiredTwos duplication.
This was being computed identically on both sides of a branch (without any variables being modified in between), so it can be lifted up, and a RYU_DEBUG line can be uncommented. The scope ends immediately afterwards.
---
Remove unnecessary parens.
Comparisons have higher precedence than logical operators and this is visually unsurprising. This removal makes it easier to see necessary parens that are overriding precedence rules, …
=> Small improvements (non-performance)

ryu/d2fixed.c, ryu/tests/d2fixed_test.cc
These are sign warnings of the form "warning C4365: '=': conversion from 'uint32_t' to 'int32_t', signed/unsigned mismatch". They're relatively noisy, but they can find unintentional value-modifying conversions (e.g. from negative signed to huge unsigned), so we test our STL with them. I found zero real issues while cleaning this up; the fine-grained commits and detailed analysis were for avoiding unintentional damage. Individual commits:
---
Fix sign warnings in d2fixed_test.cc.
d2fixed() and d2exp() take `uint32_t precision`, so `test_case` should store that type.
---
Fix sign/truncation warnings for char.
As usual, after doing math, we need to cast back to char.
---
Fix sign warnings for e2.
Like d2s.c, normal ieeeExponent values are within [1, 2046], so we should have a …
=> Fix sign warnings.

ryu/common.h
[why]
Modern compilers issue a warning, if you try to compare an unsigned
number with >=0, as this is always true. Unsigned ints can not carry
negative values.
[how]
Remove the assert and believe the type.
Signed-off-by: Fini Jastrow <ulf.fini.jastrow@desy.de>
=> common: Remove superfluous assert

ryu/BUILD
`bazel build //ryu:ryu` fails without this on my machine, and is failing in Travis as well.
https://travis-ci.org/github/ulfjack/ryu/jobs/691003011#L283
```console
ryu/f2s.c:35:10: fatal error: ryu/f2s_intrinsics.h: No such file or directory
35 | #include "ryu/f2s_intrinsics.h"
|          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //ryu:ryu failed to build
```
=> Add missing //ryu:ryu source file to Bazel target

README.md
Added a link to the scala-native project where Java version of Ryu was ported to Scala.
The jsoniter-scala library switched to the Schubfach algorithm, so the corresponding link points to the latest version of the most optimized implementation for the Ryu algorithm.
=> Update links to Scala implementations

ryu/d2s_intrinsics.h, ryu/tests/d2s_intrinsics_test.cc
1. All tests pass;
2. Overall benchmark gets slightly faster than the original; (An isolated non scientific benchmark is here https://quick-bench.com/q/eKYe8GR1GAIVBtPjy5iROUquuuw)
3. Emitted code gets shorter. (See https://godbolt.org/z/3eG8K6.)
=> Reimplemented pow5Factor using modular inverse.

README.md
Hi Ulf,
Thank you for the great algorithm!
We have only generic implementation for now.
Additional optimizations were applied:
1. Mir fixed-length integers `UInt!128` and `UInt!256`  are used instead of C's `uint128` and manual `ulong[4]` (for `uint256`). They were implemented with LLVM intrinsics and generates ideal (or almost ideal) code for multiplications.
2. /= and %= 10 operations are fused where possible and implemented using multiplication. C's `uint128` doesn't support this kind of optimization for now and performs the actual call of divide function.
3. `UInt!64` is used for `UInt!128 for `double` and `float`, all this reduces instructions size a lot.
4. #188 + minor additional optimization
5. A modification similar to #156
6. decimal length isn't used at all. Instead, we print …
=> D Ryu implementation reference

README.md
We did a port of the Java Ryu implementation to C# in J2N.
- https://github.com/NightOwl888/J2N/blob/ceaa3d17f3866a5ec4865f9be600b76c5303764c/src/J2N/Numerics/RyuDouble.cs
- https://github.com/NightOwl888/J2N/blob/ceaa3d17f3866a5ec4865f9be600b76c5303764c/src/J2N/Numerics/RyuSingle.cs
Ryu formatting is exposed through the "J" (default) format of the `ToString()` method overloads on the following public classes.
- https://github.com/NightOwl888/J2N/blob/ceaa3d17f3866a5ec4865f9be600b76c5303764c/src/J2N/Numerics/Double.cs#L2195-L3020
- https://github.com/NightOwl888/J2N/blob/ceaa3d17f3866a5ec4865f9be600b76c5303764c/src/J2N/Numerics/Single.cs#L2189-L3014
The implementation uses the Ryu algorithm to provide a round-trippable format/parse that consistently works from .NET Framework 4.0 to .NET …
=> README.md: Added additional C# implementation

CMakeLists.txt
Add a CMakeLists.txt so the ryu and general_128 libraries can be built with CMake and/or easily used by CMake-based projects.
Benefits over existing `ryu/Makefile`:
* easy control over library build options by the library user (Debug or Release, add optimization flags, add -fPIC, etc)
* Separate ryu and generic_128 libs so MSVC users can still use ryu. (generic_128 uses __uint128_t which is only available on GCC/Clang/Intel)
* easy integration with CMake projects
Usage examples:
Copy or clone the repo and use with `add_subdirectory`:
```cmake
add_subdirectory(ryu)
target_link_libraries(MY_BUILD_TARGET ryu::ryu)
```
Or fetch straight from GitHub:
```cmake
include(FetchContent)
FetchContent_Declare(
ryu
GIT_REPOSITORY https://github.com/alugowski/ryu_cmake.git
GIT_TAG master
GIT_SHALLOW …
```
=> CMake support
